package PersonaApp;


/**
* PersonaApp/personaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* miércoles 2 de mayo de 2018 09:27:36 PM COT
*/

public interface personaOperations 
{
  boolean insertarpersona (int id, String nombre, String apellidos, String direccion);
  String consultarpersona (int id);
  boolean eliminarpersona (int id);
  boolean actualizarpersona (int id, String nombre, String apellidos, String direccion);
  String listarpersona ();
  void shutdown ();
} // interface personaOperations
