package PersonaApp;


/**
* PersonaApp/persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from persona.idl
* miércoles 2 de mayo de 2018 09:27:36 PM COT
*/

public interface persona extends personaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface persona
